architecture: UNet
batch_size: 64
block_depth: 6
continue_train: 0
cuda_device: 1
dropout: 0
end_lr: 1.0e-06
epoch: 200
fields_base: Hz_forward_
fields_base_adj: Hz_adjoint_
fields_dir: /media/tmp2/metachat/data/02_deg_-5-25_n14-28_wl400-700_b3-10_l100-220_h25-50/fields
fields_dir_adj: /media/tmp2/metachat/data/02_deg_-5-25_n14-28_wl400-700_b3-10_l100-220_h25-50/fields_adj
max_wavelength: 7.0e-07
metadata_file: /media/tmp2/metachat/data/02_deg_-5-25_n14-28_wl400-700_b3-10_l100-220_h25-50/metadata.parquet
min_wavelength: 4.0e-07
model_saving_path: /media/tmp1/metachat/checkpoints/04_film_angle_dec_gen_400-700_fwd150k_adj150k_sample_otf
network_depth: 6
num_devices: 300000
num_kernels: 16
patterns_base: eps_r_
patterns_dir: /media/tmp2/metachat/data/02_deg_-5-25_n14-28_wl400-700_b3-10_l100-220_h25-50/structs
physics_start_epoch: 1
seed: 0
src_base: sources_
src_base_adj: sources_
src_dir: /media/tmp2/metachat/data/02_deg_-5-25_n14-28_wl400-700_b3-10_l100-220_h25-50/fields
src_dir_adj: /media/tmp2/metachat/data/02_deg_-5-25_n14-28_wl400-700_b3-10_l100-220_h25-50/fields_adj
start_lr: 0.0003
weight_decay: 0.003
